### PR TITLE
Maincamservo

### PR DESCRIPTION
**Pull request by AnotherOctopus**
Note, provisionally you need to revert to this kernel hash for it to work. Wiring pi does not like the latest kernel versions.
1af015c990e1d60517ac79d47ca80604e4f25196

### CODE REVIEW

**Comment by bmaxfie** [comment]
How long does this kernel change take? Have we made sure all other features (primarily i2c for thrusters and cameras) work with this reversion?

I'm going to merge rov-integration in, which should let you run.

**Comment by AnotherOctopus** [comment]
actually try this 
4ff0432eded04cad51e0bdbc77ccc9e05b74b760

**Comment by AnotherOctopus** [comment]
or this
e55262468152e6c082cdebf6face38d435a8ca44

**Comment by AnotherOctopus** [comment]
52241088c1da59a359110d39c1875cda56496764

**Comment by AnotherOctopus** [comment]
^was actually that one

**Pull request closed without merging**
