### PR TITLE
Proxy

### PR DESCRIPTION
**Pull request by AnotherOctopus**
Things the Proxy does:
Transparently handles and logs dearflask and dearclient
Allows for running of CV sideprocesses, accessing them through streams and json data
You can access all data from localhost
Adds a Client.py which gives you handles to send down JSON packets(latency is a work in progress but I think it should be resolved in a separate branch)

### CODE REVIEW

**Comment by mattmolo** [comment]
Uh, is all of the socket-io client included in this? Why? Makes it hard to review in github, but also seems weird to be included

**Comment by AnotherOctopus** [comment]
I had to modify a line in the python socketio client because there was a hard 1 second delay on the delay for the callback. Its on https://github.com/purduerov/XX-Core/blob/proxy/pakfront/testsides/socketIO-client/socketIO_client/__init__.py line 243. Probably not the most elegant way to put it in.

**Comment by bmaxfie** [comment]
Damn... I really should have started reviewing this a long time ago \*facepalm\*

**Comment by mattmolo** [comment]
@AnotherOctopus I see, does this changed also need to be done to the socket IO client used in the application.py Flask application for the ROV? If so maybe we can rehost a fork of socketIO on github and have it pull in that version for both things.

**Comment by bmaxfie** [comment]
Once you give me a little overview in person on how this works, I'd like to merge this. We can create a new PR for any more logging additions that are added.

**Comment by AnotherOctopus** [comment]
I am pretty sure the application.py uses the flask-socketio server, and is fine. This is a separate socketio-client used exclusively by pakfront/testsides/rovcontroller.py

**Comment by mattmolo** [comment]
@AnotherOctopus Oh derp, you're right.

**Review by bmaxfie — APPROVED** [review]

**Pull request merged**
