### PR TITLE
Compiler merge no tests

### PR DESCRIPTION
**Pull request by isibley765**
Two things to note (besides that reading functions in JavaScript really screw with synchronous behavior if they're asynchronous reads -- tip for the future):

1) Keith's files did something weird when I tried to merge them from development, they're claiming they're 'new' here.

2) Viktoryia asked for something in the packet file that said whether the surface had set an axis as disabled or not (we may want to talk about whether we want 'frozen'/'not frozen', or something more specific, but for now the idea is that if we want it frozen, she sees that and uses Troy(?)'s adjustment calculations to find out how to keep that axis or rotation frozen in the water from the IMU).

Other than that, this was tested against some basic cases. I'm leaving the branch surf-compiler separate so it can keep its test cases and not have them go into development. So, it can be run and tested there if you'd like to see.

### CODE REVIEW

**Comment by mattmolo** [comment]
You're 1 commit behind development, you'd need to merge so Keith's file don't show up.

**Comment by mattmolo** [comment]
Can you explain what this is supposed to do? Does this just concat html, css and js files together? Is there any big difference than just running say `cat *.html > final.main.html` in bash?

**Comment by isibley765** [comment]
Sorry Matt, this lets us make modular html files. Whenever there's a flag (#html-compiler:<path> look at the surf-compiler branch), the file of that flag gets inserted and its accompanying css and js files get concatenated as well, if they're not lined up to be already.

We're mimicking Vue's modularity.

**Comment by isibley765** [comment]
I had a merge that went wrong, so Keith's files came in but they didn't register properly I guess. I'll fix this tomorrow

**Comment by isibley765** [comment]
Fixed the merge issue, Keith's files are now not a part of this merge.

I can make this more verbose later, but this was getting something done over the weekend that we needed to make progress.
We're going to need the include statements for the final js and css files in main.html for now. If there's an aversion to that, I can make something to write them in first. Might do that after the meeting today anyways.

**Comment by mattmolo** [comment]
So, I see what you're trying to do here and what you have does seem to work. Though I have a few suggestions for the current version:
1) The component flag `#html-compiler:component_X` is a bit weird. I think it'd be much more semantic if you got `<component-X></component-X>`  or `<component-X />` working. It would fit better with syntax highlighting and other html editor features. The `#flag` way just looks a little out of place. Parsing HTML (or XHMTL) is probably annoying, but there are libraries for it. You may have to work around though ignoring common tags like `body`, `script`, etc..
2) Similar to that (and I see this is only the first version), but having multiple components on one line doesn't seem to work. You either want to fix that or maybe give an error? 
3) There also doesn't seem to be a recursive limit. (i.e., comp-1 includes comp-2, which includes comp-1 again). It most cases, I don't think you ever want to do this, so you also might want to detect that (Right now it seems to hang and gives no output). 

Other than that, sure, the current implementation seems to do what you want it to. One last suggestion for it is looking into a command line argument parser, so that you can specify configurations (root path, output, and main files maybe). Also run through `prettier --tab-width 4 --write build.js` maybe. https://github.com/prettier/prettier

**Comment by mattmolo** [comment]
Now, if you want to go with what you have use the above suggestions. But, I don't think this is a good path to go down. Right now, essentially what you have is a templating engine. It's basically hey, include this file here. Another way to do this is make all your files end in php and use `<?php include 'filename.php' ?>` instead of the compiler flag. Then just run `php main.php > final.main.html` and you're pretty much done. Either way this works, and it's fine for simple things. However, I think it's missing nearly everything that modern javascript is right now (Even though it can be a pain in the beginning, it still has some great things). For example, here's some other issues that you're going to have to work around. 

- Name collision: If someone names a javascript or css declaration the same thing, whatever gets included last overwrites it. In CSS actually, a union of the two sets will be taken. Definitely prone to very annoying bugs that are hard to debug. Vue handled this by setting up scopes (JS was defined in the components `this` scope. CSS was prepended with a random id. `<component-X>` was turned into something like `<div id="v-scoped:75n37"` and the css was then `#v-scoped:75n37<other css declarations here> { }`. Each component had its own ID randomly assigned to not conflict)

- Client side rendering/templating: Again, one of the advantages of Vue and React is that the templating is done client side in JS. Each component was actually translated into a set of javascript functions that would append and delete them depending on your model. The advantage here is that some things could be defined on the server (ROV pi) and it would react to them in the client. For example, something like the data-view component just took a json object and displayed each key:value pair in a table. Yes, you can still get this to work jquery, but it makes both the templating for components that change reactively and don't the same. Another example is making a front end that allows you to reorder components. If it's all described via some json objects, it's easy to change that and have changes reflected with React or Vue.
 
- ES2015/2016/2017, code minifiers, code shaking, etc.. Many basic webpack setups both transpile from a newer Javascript (which allows you to use better classes, async/await, other random syntactic sugar.. etc). Electron/Chrome supports most of ES6 now, but there are still a lot of other new features that you'd be missing out on. Also, there are other things it can do like a traditional compiler that optimizes the code, finds dead/unused code, minifies it. Those are things that would be pretty hard to add to this.

- includes / npm packages: For client side code, if you wanted to use one of the 100,000s packages on npm, you wouldn't be able to just `include/require` it. You'd have to find its code in node_modules, find the compiled/client version and concat that with everything else. I'm honestly not sure what magic webpack does to do this, but it's just another thing to add..

So, I think what you have is fine if you want to just do very basic templating. But I'm really suggesting you or someone else that is familiar starts to look into webpack and get something else setup. Otherwise you're losing out on a lot of features that is modern javascript app development. You don't have to use/like Vue, you can use React or marko or Angular. But you should use some framework, because the communities around them are very big, there's lot of work being put in to find bugs, a lot of beginner tutorials, and features that take care of issues you might not have known about when making it for yourself. 

If you have any questions / want to discuss more hit me up on Slack.

**Comment by isibley765** [comment]
For the 'keeping what I have' comment:
1. I actually stole that flag from a different compiler implementation that had an erroneous bug. I would agree that it stands out, but I think the idea was that it was supposed to. I think that one's up for preference, changing it to look for a html element-like item wouldn't do too much, unless we wanted to be able to add content in from the outside (depends on what we want to do -- I can't think of anything off the top of my head that we'd find that useful for, compared to last year, so we'd likely just leave it blank).
2. I was something I didn't think of, you're right, I was picturing a vertically-expanded html file. That should be... relatively easy to fix if we continue this way.
3. No, I was leaning a little bit on the smart development of our members for this first iteration. Dangerous, I know, I'll agree it needs an update for either an error or a case to accept that. Should just be a different search method and conditional function call.
4. More of a note for myself here: I was running into issues with passing some of the nodejs modules' functions as callbacks (I think line-reader's 'next()' function to grab the next line became an error when I tried to use it as a callback function, for a recursive manner*, and other small things like that), hence why I eventually reverted to this synchronous style. I didn't even think to try to use listeners, mainly because I don't think I've seen them used unless a different packet we've been using has them wrapped up in something already -- I'll be looking that up at some point here, but if you have a good resource that comes to mind I would appreciate the extra direction.

*I can go into more detail if you're interested, but short story is I tried to be at least a little more JavaScript-esk at first, which is why it took me more of this past weekend than I wanted it to.

The second comment here, I'll find you on slack for. I actually don't know php (yet), and if it's simpler I wouldn't be opposed to trading out what I made for it by any means. And the main reason we wanted to lean away from Vue is that it was very hard to debug if you didn't already know how it worked -- I started to get there and I think Ben was as well, but it was still mainly you fixing things throughout last year. I also don't want to intimidate the surface members with something they feel like they can't get a handle on, which I felt was a large part of the rest of Basestation's reaction.

I think Vue was an in-between of React and Angular if I remember correctly, and I know those two have been around much longer. I know that I could get around not using them myself most likely, but you're right, we're missing out on a lot of the features of JavaScript currently, and I don't think we have time to teach everyone well enough how to manually do all of this and still get something we want fully fleshed out for the driver. At the very least, it'd be tight, and I'd be doing the majority of it by the end.
I'm going to ask you for recommendations on frameworks (in Slack, just noting here for everyone else), and resources that aren't pay-based if you know of any.

**Comment by isibley765** [comment]
We decided that this was a limiting path to pursue, though it might work for what it was intended for. The developer (me) just didn't know I/he didn't know quite everything (thank you Matt).

Killing this so it's not still hanging around.

**Pull request closed without merging**
