### PR TITLE
prepping the code to handle controlling thrusters again

### PR DESCRIPTION
**Pull request by rmcbee**
I am adding in basic support for controlling the thrusters again. The majority of the code was copied from code last year. My plan is to use the controller class to handle connecting all of the sub control classes that have been proposed. 

I have also added the idea of using external files to store all of our magic numbers so we don't have to go deep into code every time we need to change a constant.

### CODE REVIEW

**Comment by isibley765** [comment]
It looks good as a  general sweep, as long as the thruster setting algorithm is a temporary one until we take in Drew's.

I'd also like to see more commenting, it's good for the most part, but there are a few files that don't have a single comment in them.
The README's as well should be edited if we're going to keep them. I was going to have my team use them as a general overview of the entire contents of the file (for the components at least) so that you don't have to go diving into each file to get an idea of what's going on.

We don't have to by any means, but I thought it'd be a good idea for anyone that's entirely new to the code, as well as a good method to make sure people actually know what they just did. If they're README's jargon, their code is more likely to be as well.


I've only got one other question beyond that: did you test to see that it works somehow?

**Comment by bmaxfie** [comment]
If we end up making a lot of global constants, we may want to make the constant file a configuration file with a single class to load and read the contents. We can make it in a way that once one configuration is read once, it can't be read again and will throw an error if a second read attempt is requested. This will ensure constant names aren't colliding.

**Comment by rmcbee** [comment]
@isibley765 Yeah, these files are just temporary place holders to function temporarily while I get everything setup. To you main question, no I have not tested that the code works just yet. After I got this pull request complete, I was going to create a pytest program that would test my code and verify that things are working. I did not include the test and the actual code in one file so that you did not have to do a large pull request review.

**Comment by rmcbee** [comment]
@bmaxfie For now, I will create constants files for certain sections of code and later if we want to centeralize it, we can just combine all of the constants files together. Also, there is a class in python to simulate constants that will throw errors if someone tries to change the variable.

**Comment by isibley765** [comment]
I think we need to stick to our rule that things need to be tested somehow before they get permission to be merged with development.

Its not going to be a good idea for Ben and I to keep passing exceptions, it's going to require more work in the long run.

**Comment by rmcbee** [comment]
Have there been a process set up for how you would like the code to be tested. I feel like just saying I tested it does not give a thorough understanding for how much rigor the code was tested to.

**Comment by isibley765** [comment]
Well, what were you going to do with your pytest program?

Either prove it by use (like with tools), a test script (like we had with thrusters), or something inbetween (like my gamepad testing environment). A test script for most things should be fairly appropriate, because it's able to be scaled as more is added. I think it would fit here as well, unless you have another idea that's thorough enough.

**Comment by rmcbee** [comment]
No, I 100% agree with those methods of testing. I was just wondering if we were going to have it be more formalized. I know that we can set up travis ci to make sure all test cases pass before they are able to merge. Which in some sense would include running the pytest files and making sure that the pytest files pass.

**Comment by bmaxfie** [comment]
Technically the standard is to make tests that should validate that the requirements were met. I want to make sure at the very least before code is merged to development, that it compiles. Once that requirement is met, its up to the reviewers and the owner of the code to come up with suitable tests... so like right now haha. I think with what I've seen, you should make sure (A.) that the code compiles and the rov can 'run' and connect to battle station. Then (B.) test the functionality proposed for this merge, which is simply that the basic movement algorithm works. I think test scripts are good for this as you can make varying complexity of tests separated into test case functions. For an example test case. Make sure the force vector X has expected power output vector Y.

Moving forward, basic tests should be performed before the merge request is made, and more rigorous tests can be defined during review.

**Comment by isibley765** [comment]
I might nudge Ben about some syntax enforcers, but especially if a lot of our stuff is going to be environment tested (I don't want to be the one to make a test file for the cameras and mjpeg streamer that runs through travis ci), it might not prove as useful. That, and we were able to do just fine last year. With what we're doing, and making it clear to our members that testing is required, it's usually relatively simple to come up with a way to test the code.

If you've got a good case for it, it's worth discussion at the leadership meeting, but we're not specifically requiring test code along with submissions so it starts to make less sense to get an auto-test framework.

**Comment by rmcbee** [comment]
I have added test cases to verify that the code works. The only thing that might be nebulous is the dear flask call. I used what we had last year, but it could change based on how data is sent over flask.

**Review by isibley765 — APPROVED** [review]
We'll be managing the package as we go, so the issues that come up with that will be dealt with as we go. That being said, last year's packet is going to be our basis for what we do this year, so it should be fine for now if that's what you tested with.

Tested and behavior approved, I'm pulling this in now.

**Pull request merged**
