### PR TITLE
Reactjs compiler using a Webpack/Babel compiler (finally)

### PR DESCRIPTION
**Pull request by isibley765**
Should be simple but sweet. I made it very empty here, but you can see a working version of a component being compiled with the `reactjs-example` branch.

Just make sure to run `npm install`, `npm run [build/dev]`, and `npm start` in the `frontend/` folder.

### CODE REVIEW

**Comment by isibley765** [comment]
Oh, and the packed is also updated to have a frozen axis parameter, for when we don't want to rotate or move up and down or something, so the controls team knows what to compensate for using the sensors.

**Comment by isibley765** [comment]
Potential for this to be updated later, so the styling is output into a separate css file and aren't being rendered by JavaScript, but for now it works and pursuing that (cause I did for a good while, getting errors instead) is less worth our time right now. We need to make components.

**Comment by mattmolo** [comment]
This looks good. Hopefully you're liking how React and webpack works. Before you merge you should get rid of the old components and stuff you still have in here

**Comment by isibley765** [comment]
I am, much better than the route we were going earlier.
Only thing so far is the styling, I was trying to get it to output into a css file along with the js rendering file, but I hit a conflict on the tutorial I was on.
For now the styling is rendering through JavaScript, which works for our purposes so far. I won't dive into that more til later if we have time/it proves significantly useful most likely I think.

I'll parse out the old files here soon, and then this should be ready then.

**Comment by mattmolo** [comment]
Just having one CSS file and including that with a `style` tag in your main HTML file should be okay for now.

**Pull request merged**
